import type { Metadata } from "next";
import "./globals.css";
import Header from "./_component/Header/Header";
import Footer from "./_component/Footer/Footer";
import Sidebar from "./_component/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "tech blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <div className="flex">
          {children}
          <Sidebar />
        </div>
        <Footer />
      </body>
    </html>
  );
}
